version: '3'
services:
  proxy:
    image: gnagaoka/nginx-fratello-docker:latest
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    mem_limit: 64M
    depends_on:
      - "mediawiki"
  mediawiki:
    build: .
    image: gnagaoka/ck3wiki:latest
    restart: always
    links:
      - database
    volumes:
      - ./images:/var/www/html/images
      - ./LocalSettings.php:/var/www/html/LocalSettings.php
    environment:
      DB_USER: wikiuser
      DB_PASSWORD: example
      DB_NAME: my_wiki
      DB_SERVER: database:3306
      SERVER_HOST: http://ck3.paradwiki.local
      SERVER_SECRET_KEY: 4709447dfffb3f4606ac4e6d33a12ef44d74b15fa76d08d17421474a0189bad5
      SERVER_UPGRADE_KEY: a38693f574711166
      REDIS_SERVER: redis:6379
      VIRTUAL_HOST: ck3.paradwiki.local
    mem_limit: 550M
    depends_on:
      - "database"
  database:
    image: mysql:8.0.15
    restart: always
    ports:
      - "43306:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_USER: wikiuser
      MYSQL_PASSWORD: example
      MYSQL_ROOT_PASSWORD: 1qaz2wsx
      MYSQL_DATABASE: my_wiki
    command: [
      --character-set-server=utf8mb4,
      --collation-server=utf8mb4_general_ci,
      --default-storage-engine=innodb
    ]
    depends_on:
      - "observer"
  observer:
    image: google/cadvisor:latest
    expose:
      - 8092
    ports: 
      - 8092:8080
    restart: always
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    command: --storage_driver=influxdb --storage_driver_host=influxdb:8086 --storage_driver_secure=False
    depends_on:
      - "influxdb"
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
  influxdb:
    image: influxdb
    volumes:
      - ./influxdb:/var/lib/influxdb
    ports:
      - 8086:8086
  redis:
    image: redis:latest
    ports:
      - "46379:6379"
    command: redis-server --appendonly yes
    volumes:
      - ./data/redis:/data